version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/debian/bookworm"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "debian"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "docker"
    directories:
      - "/debian/trixie"
      - "/ubuntu/26.04"
    schedule:
      interval: "weekly"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"